---
name: workflow

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker-compose build
      - name: Test
        run: docker-compose run --rm app sh -c "python ./book_my_show/manage.py wait_for_db && python ./book_my_show/manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8 --ignore F401,E501" 